    kind: pipeline
    type: docker
    name: amd64-gcc
    platform: 
      arch: amd64
      
    steps:
    - name: build-gcc
      image: ubuntu:bionic
      commands:
      - apt-get update -y
      - apt-get install -y g++ cmake libtbb-dev libcurl4-openssl-dev libace-dev git libmysql++-dev
      - export TBB_ROOT_DIR=/usr/include/tbb/
      - export ACE_ROOT=/usr/include/ace/
      - mkdir build
      - cd build
      - cmake -DDEBUG=0 -DUSE_LIBCURL=1 ..
      - make -j$(nproc)
      
    ---
    kind: pipeline
    type: docker
    name: amd64-clang

    steps:
    - name: build-clang
      image: ubuntu:bionic
      commands:
      - apt-get update -y
      - apt-get install -y clang cmake libtbb-dev libcurl4-openssl-dev libace-dev git libmysql++-dev
      - export CC=/usr/bin/clang
      - export CXX=/usr/bin/clang++
      - mkdir build
      - cd build
      - cmake -DDEBUG=0 -DUSE_LIBCURL=1 ..
      - make -j$(nproc)
